version: "3.8"


services:

  mongo-ce:
    image: mongo:6.0
    container_name: formio-mongo-ce
    restart: unless-stopped
    volumes:
      - "./data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME:••••••••••
      MONGO_INITDB_ROOT_PASSWORD:••••••••••
      MONGO_INITDB_DATABASE:formio-ce
    networks:
      - formio-ce


  formio-ce:
    image: formio/formio:rc
    container_name: formio-ce
    restart: always
    depends_on: 
      - mongo-ce
    ports:
      - "3001:3001"
    environment:
      MONGO: mongodb://••••••••••:••••••••••@mongo-ce:27017/formio-ce
      PORT: 3001
      JWT_SECRET: ••••••••••
    networks:
      - formio-ce


networks:
  formio-ce:
    driver: bridge
